language: node_js
node_js:
  - "lts/*"
script:
  - npm run build
cache:
  directories:
    - "node_modules"
before_deploy:
  - npm install now --no-save
  - now remove noonpacificfeed --safe --yes --team noonpacificfeed --token $NOW_TOKEN || true
deploy:
  - provider: script
    script: now --name noonpacificfeed --public --team noonpacificfeed --token $NOW_TOKEN && now alias noonpacificfeed --team noonpacificfeed --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true